-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 20:04:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pomieszczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pomieszczenia` (
  `idPomieszczenia` INT NOT NULL,
  `numerPomieszczenia` VARCHAR(45) NOT NULL,
  `pietro` INT NOT NULL,
  `pojemnosc` INT NULL,
  `czyStanowiskaKomputerowe` TINYINT NULL,
  `czyRzutnik` TINYINT NULL,
  PRIMARY KEY (`idPomieszczenia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik` (
  `idPracownik` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Konsultacje` INT NULL,
  `Pracownikcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPracownik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Konsultacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Konsultacja` (
  `idKonsultacja` INT NOT NULL,
  `dzienTygodnia` INT NOT NULL,
  `godzinaRozpoczecia` TIMESTAMP NOT NULL,
  `godzinaZakonczenia` TIMESTAMP NOT NULL,
  `Pracownik_idPracownik` INT NOT NULL,
  `Pomieszczenia_idPomieszczenia` INT NOT NULL,
  PRIMARY KEY (`idKonsultacja`, `Pomieszczenia_idPomieszczenia`),
  INDEX `fk_Konsultacja_Pracownik1_idx` (`Pracownik_idPracownik` ASC) VISIBLE,
  INDEX `fk_Konsultacja_Pomieszczenia1_idx` (`Pomieszczenia_idPomieszczenia` ASC) VISIBLE)
ENGINE = FEDERATED;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik_ma_dostep_do_Pomieszczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik_ma_dostep_do_Pomieszczenia` (
  `Pracownik_idPracownik` INT NOT NULL,
  `Pracownik_Konsultacja_idKonsultacja` INT NOT NULL,
  `Pomieszczenia_idPomieszczenia` INT NOT NULL,
  PRIMARY KEY (`Pracownik_idPracownik`, `Pracownik_Konsultacja_idKonsultacja`, `Pomieszczenia_idPomieszczenia`),
  INDEX `fk_Pracownik_has_Pomieszczenia_Pomieszczenia1_idx` (`Pomieszczenia_idPomieszczenia` ASC) VISIBLE,
  INDEX `fk_Pracownik_has_Pomieszczenia_Pracownik1_idx` (`Pracownik_idPracownik` ASC, `Pracownik_Konsultacja_idKonsultacja` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_has_Pomieszczenia_Pracownik1`
    FOREIGN KEY (`Pracownik_idPracownik`)
    REFERENCES `mydb`.`Pracownik` (`idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownik_has_Pomieszczenia_Pomieszczenia1`
    FOREIGN KEY (`Pomieszczenia_idPomieszczenia`)
    REFERENCES `mydb`.`Pomieszczenia` (`idPomieszczenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `nrIndeksu` INT NULL,
  `kodKreskowyLegitymacji` INT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zajęcia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zajęcia` (
  `idZajęcia` INT NOT NULL,
  `NazwaPrzedmiotu` VARCHAR(45) NULL,
  `TypZajec` VARCHAR(45) NULL COMMENT 'wykład/lab/proj\n',
  `dzienTygodnia` INT NULL,
  `godzinaRozpoczecia` TIMESTAMP NULL,
  `godzinaZakonczenia` TIMESTAMP NULL,
  `Pomieszczenia_idPomieszczenia` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`idZajęcia`, `Pomieszczenia_idPomieszczenia`),
  INDEX `fk_Zajęcia_Pomieszczenia1_idx` (`Pomieszczenia_idPomieszczenia` ASC) VISIBLE,
  INDEX `fk_Zajęcia_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Zajęcia_Pomieszczenia1`
    FOREIGN KEY (`Pomieszczenia_idPomieszczenia`)
    REFERENCES `mydb`.`Pomieszczenia` (`idPomieszczenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajęcia_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik_odwiedzil_Pomieszczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik_odwiedzil_Pomieszczenia` (
  `Pracownik_idPracownik` INT NOT NULL,
  `Pomieszczenia_idPomieszczenia` INT NOT NULL,
  `kiedyUzylTuKarty` TIMESTAMP NULL COMMENT 'format danych czasowych wszedzie do rozkminienia\n',
  PRIMARY KEY (`Pracownik_idPracownik`, `Pomieszczenia_idPomieszczenia`),
  INDEX `fk_Pracownik_has_Pomieszczenia_Pomieszczenia2_idx` (`Pomieszczenia_idPomieszczenia` ASC) VISIBLE,
  INDEX `fk_Pracownik_has_Pomieszczenia_Pracownik2_idx` (`Pracownik_idPracownik` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_has_Pomieszczenia_Pracownik2`
    FOREIGN KEY (`Pracownik_idPracownik`)
    REFERENCES `mydb`.`Pracownik` (`idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownik_has_Pomieszczenia_Pomieszczenia2`
    FOREIGN KEY (`Pomieszczenia_idPomieszczenia`)
    REFERENCES `mydb`.`Pomieszczenia` (`idPomieszczenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik_has_Zajęcia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik_has_Zajęcia` (
  `Pracownik_idPracownik` INT NOT NULL,
  `Zajęcia_idZajęcia` INT NOT NULL,
  `Zajęcia_Pomieszczenia_idPomieszczenia` INT NOT NULL,
  PRIMARY KEY (`Pracownik_idPracownik`, `Zajęcia_idZajęcia`, `Zajęcia_Pomieszczenia_idPomieszczenia`),
  INDEX `fk_Pracownik_has_Zajęcia_Zajęcia1_idx` (`Zajęcia_idZajęcia` ASC, `Zajęcia_Pomieszczenia_idPomieszczenia` ASC) VISIBLE,
  INDEX `fk_Pracownik_has_Zajęcia_Pracownik1_idx` (`Pracownik_idPracownik` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_has_Zajęcia_Pracownik1`
    FOREIGN KEY (`Pracownik_idPracownik`)
    REFERENCES `mydb`.`Pracownik` (`idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownik_has_Zajęcia_Zajęcia1`
    FOREIGN KEY (`Zajęcia_idZajęcia` , `Zajęcia_Pomieszczenia_idPomieszczenia`)
    REFERENCES `mydb`.`Zajęcia` (`idZajęcia` , `Pomieszczenia_idPomieszczenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
